lumi: 41800
TriggerChannels:
    - Triggers_HZZ4l

Triggers_HZZ4l:
    - event.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL
    - event.HLT_DoubleEle25_CaloIdL_MW
    - event.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
    - event.HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
    - event.HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    - event.HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    - event.HLT_DiMu9_Ele9_CaloIdL_TrackIdL_DZ
    - event.HLT_Mu8_DiEle12_CaloIdL_TrackIdL_DZ
    - event.HLT_TripleMu_10_5_5_DZ
    - event.HLT_TripleMu_12_10_5
    - event.HLT_Ele30_WPTight_Gsf
    - event.HLT_IsoMu24

Zmass: 91.1876
MZ1cut: 40
MZcut:
    down:   12
    up: 120
MZZcut: 70
Higgscut:
    up: 160
    down: 105

Electron:
    pTcut: 7
    Etacut: 2.5
    Sip3dcut: 4
    Loosedxycut: 0.5
    Loosedzcut: 1
    BDTWP:
        LowEta:
            LowPT: 0.926614978724
            HighPT: 0.352678981617
        MedEta:
            LowPT: 0.913768989002
            HighPT: 0.260085399397
        HighEta:
            LowPT: 0.968212252285
            HighPT: -0.496311372876
    Isocut: 0.35
Muon:
    pTcut: 5
    Etacut: 2.4
    Sip3dcut: 4
    Loosedxycut: 0.5
    Loosedzcut: 1
    Tightdxycut: 0.2
    Tightdzcut: 0.5
    TightTrackerLayercut: 5
    TightpTErrorcut: 0.3
    HighPtBound: 200
    Isocut: 0.35

FsrPhoton:
    pTcut: 2
    Etacut: 2.4
    Isocut: 0.8
    dRlcut: 0.5
    dRlOverPtcut: 0.012

Jet:
    pTcut: 30
    Etacut: 4.7
    deepJet_btag:
        Loose: 0.0494
        Medium: 0.2770
        Tight: 0.7264


HZZ2l2q:
    Leading_Lep_pT: 40
    SubLeading_Lep_pT: 24
    Lep_eta: 2.4
    MZLepcut:
        down: 60
        up: 120

HZZ2l2nu:
    Leading_Lep_pT: 25.0
    SubLeading_Lep_pT: 25.0
    Lep_eta: 2.5
    Pt_ll: 10.0
    M_ll_Window: 15.0
    dPhi_jetMET: 0.0
    MZLepcut:
        down: 60.0
        up: 120.0


inputdataNPV: "data/pileupHistogram-Cert_Collisions2022_355100_362760_GoldenJson-13p6TeV-69200ub-99bins.root"
inputdataNPVup: "data/pileupHistogram-Cert_Collisions2022_355100_362760_GoldenJson-13p6TeV-72400ub-99bins.root"
inputdataNPVdown: "data/pileupHistogram-Cert_Collisions2022_355100_362760_GoldenJson-13p6TeV-66000ub-99bins.root"

"outputdataNPV": "data/pileupHistogram_2022.root"
outputdataNPVup: "data/pileupHistogram_2022up.root"
outputdataNPVdown: "data/pileupHistogram_2022down.root"

PUweightHistoName: "pileupWeight"
